export const more = {
  signalsAll: ["All", "Все"],
  signalsStandard: ["Main / other", "Поездные / прочие"],
  shuntingSignals: ["Shunting signals", "Маневровые сигналы"],
  showShuntingSignals: [
    "Show shunting signals on map",
    "Маневровые сигналы на карте",
  ],
  signalCategory: ["Signal category", "Категория сигнала"],
  displayOnly: [
    "Display only. Game signal operation is unchanged.",
    "Только отображение. Работа игровых сигналов не меняется.",
  ],
  details: ["Object details", "Сведения об объекте"],
  toggleSidebar: ["Collapse object list", "Свернуть список объектов"],
  objectLists: ["Object lists", "Разделы объектов"],
  filter: ["Filter", "Фильтр"],
  sort: ["Sort", "Сортировка"],
  zoomIn: ["Zoom in", "Приблизить"],
  zoomOut: ["Zoom out", "Отдалить"],
  mapControls: [
    "Railway map. Drag to pan; scroll to zoom.",
    "Схема путей. Перетаскивание — перемещение, колесо — масштаб.",
  ],
  RESERVATION_UNAVAILABLE: [
    "This signal cannot reserve tracks",
    "Этот сигнал не поддерживает резервирование путей",
  ],

  startTime: ["Start time", "Время начала"],
  ownerLocal: ["Local player", "Игрок одиночной игры"],
  ownerShared: ["Shared job", "Общий заказ"],
  ownerAssigned: ["Assigned player", "Назначен игроку"],
  ownerUnassigned: ["Not assigned", "Не назначен"],
  ownerUnavailable: ["Not specified", "Не указан"],
  notStarted: ["Not accepted", "Не принят"],
  startedAgo: ["{time} ago (game time)", "{time} назад (игровое время)"],
  gameTimeLabel: ["game time", "игровое время"],
  startNotRecorded: ["Not recorded", "Не зафиксировано"],
  jobLeftOrigin: [
    "All observed order cars left the origin station",
    "Все наблюдаемые вагоны заказа покинули станцию отправления",
  ],
  jobEnteredDestination: [
    "Order cars entered the destination station",
    "Вагоны заказа вошли на станцию назначения",
  ],
  captureError: ["Game data capture failed", "Ошибка чтения игровых данных"],
  Methane: ["Methane", "Метан"],
  Plywood: ["Plywood", "Фанера"],
  Sleepers: ["Sleepers", "Шпалы"],
  Corn: ["Corn", "Кукуруза"],
  SunflowerSeeds: ["Sunflower Seeds", "Семена подсолнечника"],
  Pigs: ["Pigs", "Свиньи"],
  Cows: ["Cows", "Коровы"],
  Poultry: ["Poultry", "Домашняя птица"],
  Sheep: ["Sheep", "Овцы"],
  Goats: ["Goats", "Козы"],
  Fish: ["Fish", "Рыба"],
  Bread: ["Bread", "Хлеб"],
  DairyProducts: ["Dairy Products", "Молочные продукты"],
  MeatProducts: ["Meat Products", "Мясные продукты"],
  CannedFood: ["Canned Food", "Консервы"],
  CatFood: ["Cat Food", "Кошачий корм"],
  TemperateFruits: ["Temperate Fruits", "Фрукты умеренного климата"],
  Vegetables: ["Vegetables", "Овощи"],
  Milk: ["Milk", "Молоко"],
  Eggs: ["Eggs", "Яйца"],
  Cotton: ["Cotton", "Хлопок"],
  Wool: ["Wool", "Шерсть"],
  TropicalFruits: ["Tropical Fruits", "Тропические фрукты"],
  SteelBillets: ["Steel Billets", "Стальные заготовки"],
  SteelBentPlates: ["Steel Bent Plates", "Гнутые стальные листы"],
  SteelRails: ["Steel Rails", "Стальные рельсы"],
  ScrapWood: ["Scrap Wood", "Древесные отходы"],
  WoodChips: ["Wood Chips", "Щепа"],
  ScrapContainers: ["Scrap Containers", "Списанные контейнеры"],
  ElectronicsIskar: ["Electronics Iskar", "Электроника Iskar"],
  ElectronicsKrugmann: ["Electronics Krugmann", "Электроника Krugmann"],
  ElectronicsAAG: ["Electronics AAG", "Электроника AAG"],
  ElectronicsNovae: ["Electronics Novae", "Электроника Novae"],
  ElectronicsTraeg: ["Electronics Traeg", "Электроника Traeg"],
  ToolsIskar: ["Tools Iskar", "Инструменты Iskar"],
  ToolsBrohm: ["Tools Brohm", "Инструменты Brohm"],
  ToolsAAG: ["Tools AAG", "Инструменты AAG"],
  ToolsNovae: ["Tools Novae", "Инструменты Novae"],
  ToolsTraeg: ["Tools Traeg", "Инструменты Traeg"],
  Furniture: ["Furniture", "Мебель"],
  Pipes: ["Pipes", "Трубы"],
  ClothingObco: ["Clothing Obco", "Одежда Obco"],
  ClothingNeoGamma: ["Clothing Neo Gamma", "Одежда NeoGamma"],
  ClothingNovae: ["Clothing Novae", "Одежда Novae"],
  ClothingTraeg: ["Clothing Traeg", "Одежда Traeg"],
  Medicine: ["Medicine", "Лекарства"],
  ChemicalsIskar: ["Chemicals Iskar", "Химикаты Iskar"],
  ChemicalsSperex: ["Chemicals Sperex", "Химикаты Sperex"],
  ImportedNewCars: ["Imported New Cars", "Импортные автомобили"],
  Tractors: ["Tractors", "Тракторы"],
  Excavators: ["Excavators", "Экскаваторы"],
  MiningTrucks: ["Mining Trucks", "Карьерные самосвалы"],
  CityBuses: ["City Buses", "Городские автобусы"],
  SemiTrailers: ["Semi Trailers", "Полуприцепы"],
  CraneParts: ["Crane Parts", "Детали крана"],
  Trams: ["Trams", "Трамваи"],
  ForestryTrailers: ["Forestry Trailers", "Лесовозные прицепы"],
  Acetylene: ["Acetylene", "Ацетилен"],
  CryoOxygen: ["Cryo Oxygen", "Жидкий кислород"],
  CryoHydrogen: ["Cryo Hydrogen", "Жидкий водород"],
  Argon: ["Argon", "Аргон"],
  Nitrogen: ["Nitrogen", "Азот"],
  Ammonia: ["Ammonia", "Аммиак"],
  SodiumHydroxide: ["Sodium Hydroxide", "Гидроксид натрия"],
  AmmoniumNitrate: ["Ammonium Nitrate", "Аммиачная селитра"],
  SpentNuclearFuel: ["Spent Nuclear Fuel", "Отработанное ядерное топливо"],
  Ammunition: ["Ammunition", "Боеприпасы"],
  Biohazard: ["Biohazard", "Биологически опасные вещества"],
  Tanks: ["Tanks", "Танки"],
  MilitaryTrucks: ["Military Trucks", "Военные грузовики"],
  MilitarySupplies: ["Military Supplies", "Военные припасы"],
  AttackHelicopters: ["Attack Helicopters", "Боевые вертолёты"],
  Missiles: ["Missiles", "Ракеты"],
  MilitaryCars: ["Military Cars", "Военные автомобили"],
  TrainPartsDE2: ["Train Parts DE2", "Детали локомотива DE2"],
  TrainPartsDE6: ["Train Parts DE6", "Детали локомотива DE6"],
  TrainPartsDH4: ["Train Parts DH4", "Детали локомотива DH4"],
  TrainPartsDM3: ["Train Parts DM3", "Детали локомотива DM3"],
  TrainPartsS060: ["Train Parts S060", "Детали локомотива S060"],
  TrainPartsS282A: ["Train Parts S282A", "Детали локомотива S282A"],
  EmptySunOmni: ["Empty Sun Omni", "Пустые контейнеры SunOmni"],
  EmptyIskar: ["Empty Iskar", "Пустые контейнеры Iskar"],
  EmptyObco: ["Empty Obco", "Пустые контейнеры Obco"],
  EmptyGoorsk: ["Empty Goorsk", "Пустые контейнеры Goorsk"],
  EmptyKrugmann: ["Empty Krugmann", "Пустые контейнеры Krugmann"],
  EmptyBrohm: ["Empty Brohm", "Пустые контейнеры Brohm"],
  EmptyAAG: ["Empty AAG", "Пустые контейнеры AAG"],
  EmptySperex: ["Empty Sperex", "Пустые контейнеры Sperex"],
  EmptyNovae: ["Empty Novae", "Пустые контейнеры Novae"],
  EmptyTraeg: ["Empty Traeg", "Пустые контейнеры Traeg"],
  EmptyChemlek: ["Empty Chemlek", "Пустые контейнеры Chemlek"],
  EmptyNeoGamma: ["Empty Neo Gamma", "Пустые контейнеры NeoGamma"],
  alongTrack: ["Track start → end", "От начала пути к концу"],
  againstTrack: ["Track end → start", "От конца пути к началу"],

  reserveRouteSignals: ["Reserve route", "Резервировать маршрут"],
  releaseRouteSignals: [
    "Release route signal reservations",
    "Снять резервы сигналов маршрута",
  ],
  Failed: ["Task failed", "Задача не выполнена"],
  Military3: ["Military III", "Военные грузы III"],
  TrainLength1: ["Train length I", "Длина состава I"],
  TrainLength2: ["Train length II", "Длина состава II"],
  Shunting: ["Shunting", "Маневровые работы"],
  LogisticalHaul: ["Logistical Haul", "Логистическая перевозка"],
  Fragile: ["Fragile cargo", "Хрупкий груз"],
  ComplexTransport: ["Complex transport", "Сложная перевозка"],

  displaySettings: ["Display", "Отображение"],
  automaticLanguage: [
    "Language follows the host game's language. Other languages use English.",
    "Язык следует языку игры хоста. Для остальных языков используется английский.",
  ],
  interfaceScale: ["Interface scale", "Масштаб интерфейса"],
  textScale: ["Interface text", "Текст интерфейса"],
  labelScale: ["Map labels", "Подписи карты"],
  trainLabelScale: ["Rolling stock labels", "Подписи подвижного состава"],
  signalScale: ["Signal head size", "Размер светофоров"],
  trainScale: ["Rolling stock icon size", "Размер значков подвижного состава"],
  switchScale: ["Turnout icon size", "Размер значков стрелок"],
  blockLabelScale: ["Track block label size", "Подписи путевых блоков"],
  renderRate: ["Map frame limit", "Частота кадров карты"],
  mapScale: ["Map zoom", "Масштаб карты"],
  resetDisplay: ["Reset display settings", "Сбросить параметры отображения"],
  stations: ["Stations", "Станции"],
  industries: ["Industries", "Промышленность"],
  reservations: ["Reservations", "Резервации"],
  speedLimits: ["Speed limits", "Ограничения скорости"],
  speedRestrictions: ["Speed sections", "Скоростные участки"],
  signs: ["Signs", "Знаки"],
  technical: ["Technical IDs", "Технические ID"],
  blockLabels: ["Track block labels", "Подписи путевых блоков"],
  occupiedBlocks: ["Occupied track sets", "Занятые группы путей"],
  stopSignals: ["Stop signals", "Запрещающие сигналы"],
  activeOrders: ["Active orders", "Активные заказы"],
  warnings: ["Warnings", "Предупреждения"],
  moreActiveOrders: ["More in the list", "Ещё в списке"],
  all: ["All", "Все"],
  sort_name: ["By name", "По имени"],
  sort_speed: ["By speed", "По скорости"],
  sort_status: ["By status", "По состоянию"],
  sort_recent: ["Newest first", "Сначала новые"],
  Available: ["Available", "Доступен"],
  InProgress: ["In progress", "Выполняется"],
  Completed: ["Completed", "Выполнен"],
  Abandoned: ["Abandoned", "Отменён"],
  Expired: ["Expired", "Истёк"],
  NotStarted: ["Not started", "Не начата"],
  Ongoing: ["In progress", "Выполняется"],
  Done: ["Done", "Завершена"],
  owner: ["Job owner", "Владелец заказа"],
  jobType: ["Order type", "Тип заказа"],
  cargo: ["Cargo", "Груз"],
  tasks: ["tasks", "задач"],
  progress: ["Task progress", "Прогресс задач"],
  elapsed: ["Elapsed game time", "Прошло игрового времени"],
  bonus: ["Potential bonus", "Возможная премия"],
  bonusTime: ["Bonus time remaining", "До окончания срока премии"],
  bonusExpired: ["Bonus time expired", "Срок премии истёк"],
  bonusExplanation: [
    "The timer is the game's bonus window, including its 60-second grace period. Expiry does not fail the order.",
    "Таймер показывает срок игровой премии с запасом 60 секунд. Истечение срока не означает провал заказа.",
  ],
  currentBlock: ["Current track block", "Текущий путевой блок"],
  currentLocation: ["Current location", "Текущее положение"],
  nextSignal: ["Next signal", "Следующий сигнал"],
  aboard: ["Players aboard", "Игроки в составе"],
  eventHistory: ["Observed history", "Наблюдаемая история"],
  couplingRequired: ["Coupling is still required", "Требуется сцепка"],
  handbrakeRequired: [
    "A handbrake is still required",
    "Требуется ручной тормоз",
  ],
  routeToTask: ["Route to this task", "Маршрут к этой задаче"],
  routeFromTrain: ["Route from consist", "Маршрут от состава"],
  calculateRoute: ["Calculate", "Рассчитать"],
  selectValidTrack: [
    "Choose a track from the suggestions",
    "Выберите путь из подсказок",
  ],
  routeDetails: ["Route details", "Подробности маршрута"],
  itinerary: ["Route sequence", "Последовательность маршрута"],
  remainingDistance: ["Remaining distance", "Оставшееся расстояние"],
  OPPOSING_TRAIN: ["Opposing train on route", "Встречный поезд на маршруте"],
  SIGNAL_STOP: ["Signal shows stop", "Сигнал запрещает движение"],
  SIGNAL_OFF: ["Signal is off", "Сигнал выключен"],
  BLOCK_OCCUPIED: ["Track block is occupied", "Путевой блок занят"],
  SWITCH_PLAN_CONFLICT: [
    "Other plan needs a different switch position",
    "Другому плану нужно иное положение стрелки",
  ],
  TRAIN_OFF_ROUTE: [
    "Train has left the planned route",
    "Поезд покинул запланированный маршрут",
  ],
  TRAIN_OPPOSITE_ROUTE: [
    "Train is moving against the planned direction",
    "Поезд движется против направления маршрута",
  ],
  TRAIN_UNAVAILABLE: [
    "Route train is no longer available",
    "Поезд маршрута больше недоступен",
  ],
  passingSpeed: ["Signal passing speed", "Скорость по сигналу"],
  connectedTracks: ["Connected tracks", "Соединённые пути"],
  lock: ["Switch locking", "Блокировка стрелки"],
  unrestricted: [
    "Gameplay switching is allowed",
    "Игровые переключения разрешены",
  ],
  controller: ["Control", "Управление"],
  sharedControls: [
    "Shared with game controls",
    "Общее с игровыми органами управления",
  ],
  advanceWarning: [
    "Advance indication; not a current limit",
    "Предварительное указание; не текущее ограничение",
  ],
  "native-scene": ["Verified game scene", "Проверенная игровая сцена"],
  "native-live": ["Observed game sign", "Наблюдаемый игровой знак"],
  type: ["Type", "Тип"],
  severity: ["Severity", "Важность"],
  actor: ["Actor", "Инициатор"],
  target: ["Object", "Объект"],
  message: ["Message", "Сообщение"],
  info: ["Information", "Информация"],
  error: ["Error", "Ошибка"],
  system: ["System", "Система"],
  train: ["Consist", "Состав"],
  signal: ["Signal", "Сигнал"],
  block: ["Track block", "Путевой блок"],
  switch: ["Switch", "Стрелка"],
  route: ["Route", "Маршрут"],
  player: ["Player", "Игрок"],
  command: ["Command", "Команда"],
  game: ["Game", "Игра"],
  signalChanged: ["Signal changed", "Сигнал изменился"],
  blockChanged: ["Track block changed", "Состояние путевого блока изменилось"],
  trainEnteredBlock: [
    "Train entered track block",
    "Поезд вошёл в путевой блок",
  ],
  trainLeftBlock: ["Train left track block", "Поезд вышел из путевого блока"],
  reservationMade: ["Native reservation made", "Игровой резерв установлен"],
  reservationReleased: ["Native reservation released", "Игровой резерв снят"],
  playerConnected: ["Player appeared in world", "Игрок появился в мире"],
  playerDisconnected: ["Player left world", "Игрок покинул мир"],
  jobInProgress: ["Order started", "Заказ начат"],
  jobCompleted: ["Order completed", "Заказ выполнен"],
  jobAbandoned: ["Order abandoned", "Заказ отменён"],
  jobExpired: ["Order expired", "Срок заказа истёк"],
  jobAvailable: ["Order available", "Заказ доступен"],
  jobTaskDone: ["Order task completed", "Задача заказа выполнена"],
  cargoTaskDone: ["Cargo task completed", "Грузовая задача выполнена"],
  transportTaskDone: ["Transport task completed", "Задача перевозки выполнена"],
  Transport: ["Transport", "Перевозка"],
  Warehouse: ["Warehouse operation", "Складская операция"],
  Sequential: ["Sequential tasks", "Последовательные задачи"],
  Parallel: ["Parallel tasks", "Параллельные задачи"],
  Couple: ["Couple", "Сцепка"],
  Uncouple: ["Uncouple", "Расцепка"],
  Custom: ["Custom", "Особая"],
  None: ["None", "Нет"],
  FreightHaul: ["Freight haul", "Грузовая перевозка"],
  ShuntingLoad: ["Shunting: load", "Маневровая: погрузка"],
  ShuntingUnload: ["Shunting: unload", "Маневровая: разгрузка"],
  LogisticHaul: ["Logistical Haul", "Логистическая перевозка"],
  Passenger: ["Passenger service", "Пассажирская перевозка"],
  PassengerHaul: ["Passenger service", "Пассажирская перевозка"],
  EmptyHaul: ["Logistical Haul", "Логистическая перевозка"],
  Basic: ["Basic", "Базовая"],
  Long1: ["Length I", "Длина I"],
  Long2: ["Length II", "Длина II"],
  Hazmat1: ["Hazmat I", "Опасные грузы I"],
  Hazmat2: ["Hazmat II", "Опасные грузы II"],
  Hazmat3: ["Hazmat III", "Опасные грузы III"],
  Military1: ["Military I", "Военные грузы I"],
  Military2: ["Military II", "Военные грузы II"],
  ConcurrentJobs1: ["Concurrent jobs I", "Параллельные заказы I"],
  ConcurrentJobs2: ["Concurrent jobs II", "Параллельные заказы II"],
  SpeedLimit: ["Speed limit", "Ограничение скорости"],
  SpeedLimitOld: ["Speed limit", "Ограничение скорости"],
  SpeedLimitYellow: ["Yellow speed sign", "Жёлтый скоростной знак"],
  SpeedLimitYellowOld: ["Yellow speed sign", "Жёлтый скоростной знак"],
  UpcomingJunction: ["Upcoming junction", "Впереди стрелка"],
  UpcomingJunctionOld: ["Upcoming junction", "Впереди стрелка"],
  UpcomingTrackEnd: ["Upcoming track end", "Конец пути"],
  UpcomingTrackEndOld: ["Upcoming track end", "Конец пути"],
  UpcomingSpeedUp: ["Upcoming speed increase", "Впереди повышение скорости"],
  UpcomingSpeedDown: ["Upcoming speed decrease", "Впереди снижение скорости"],
  UpcomingSpeedUpOld: ["Upcoming speed increase", "Впереди повышение скорости"],
  UpcomingSpeedDownOld: [
    "Upcoming speed decrease",
    "Впереди снижение скорости",
  ],
  ArrowLeft: ["Left branch", "Левая ветвь"],
  ArrowRight: ["Right branch", "Правая ветвь"],
  GradeUp: ["Uphill", "Подъём"],
  GradeDown: ["Downhill", "Спуск"],
  GradeFlat: ["Level", "Ровный участок"],
  GradeUpOld: ["Uphill", "Подъём"],
  GradeDownOld: ["Downhill", "Спуск"],
  GradeFlatOld: ["Level", "Ровный участок"],
  Tunnel: ["Tunnel", "Тоннель"],
  TunnelOld: ["Tunnel", "Тоннель"],
  RectRed: ["Red plate", "Красная табличка"],
  RectWhite: ["White plate", "Белая табличка"],
  TrackID: ["Track ID", "Номер пути"],
  JunctionLeft: ["Junction left", "Стрелка влево"],
  JunctionRight: ["Junction right", "Стрелка вправо"],
  Coal: ["Coal", "Уголь"],
  IronOre: ["Iron ore", "Железная руда"],
  CrudeOil: ["Crude oil", "Сырая нефть"],
  SteelRolls: ["Steel rolls", "Рулоны стали"],
  SteelPlates: ["Steel plates", "Листовая сталь"],
  SteelSlabs: ["Steel slabs", "Стальные слябы"],
  Rails: ["Rails", "Рельсы"],
  Logs: ["Logs", "Брёвна"],
  Boards: ["Boards", "Доски"],
  Wheat: ["Wheat", "Пшеница"],
  Flour: ["Flour", "Мука"],
  Food: ["Food", "Продукты"],
  Oil: ["Oil", "Нефть"],
  Diesel: ["Diesel", "Дизельное топливо"],
  Gasoline: ["Gasoline", "Бензин"],
  Alcohol: ["Alcohol", "Спирт"],
  Chemicals: ["Chemicals", "Химикаты"],
  Cars: ["Cars", "Автомобили"],
  NewCars: ["New cars", "Новые автомобили"],
  ScrapMetal: ["Scrap metal", "Металлолом"],
  Empty: ["Empty", "Порожний"],
  Passengers: ["Passengers", "Пассажиры"],
};
