<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net48</TargetFramework><AssemblyName>AdvancedDispatcherSystem.Passenger</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AdvancedDispatcherSystem.Game/AdvancedDispatcherSystem.Game.csproj" />
    <Reference Include="$(GameRoot)/Mods/PassengerJobs/PassengerJobs.dll"><Private>false</Private></Reference>
    <Reference Include="$(GameRoot)/DerailValley_Data/Managed/*.dll" Exclude="$(GameRoot)/DerailValley_Data/Managed/mscorlib.dll;$(GameRoot)/DerailValley_Data/Managed/System*.dll;$(GameRoot)/DerailValley_Data/Managed/Mono.*.dll;$(GameRoot)/DerailValley_Data/Managed/Microsoft.*.dll;$(GameRoot)/DerailValley_Data/Managed/netstandard.dll"><Private>false</Private></Reference>
  </ItemGroup>
</Project>
